[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = false

[runner]
fastReruns = true
magicEnabled = true
installTracer = false
